#!/bin/sh -e

echo "docker push $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:${IMAGE_TAG-latest}"
docker login -u $DOCKER_USER -p $DOCKER_PASSWORD -e $DOCKER_EMAIL $DOCKER_REGISTRY
docker tag $IMAGE_NAME $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:${IMAGE_TAG-latest}
docker push $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:${IMAGE_TAG-latest}
